# Extra env variables
# env = MY_GLOBAL_ENV,setting

env = TERMINAL,kitty
env = SHELL,/usr/bin/zsh
env = ANDROID_SDK_ROOT=/opt/android-sdk
env = ANDROID_HOME=$ANDROID_SDK_ROOT
env = PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator"

