# List of packages to be installed
#
# Browsers
firefox
brave-bin

# Shell
zsh

# Terminal Emulator
kitty

# File Manager
thunar

# Email Client
thunderbird

# Text Editor
neovim
visual-studio-code-bin
obsidian

# System Monitoring Tools
htop
btop
nvtop
radeontop

# Networking Tools
curl
wget
postman-bin
net-tools
openbsd-netcat

# Programming Languages and Runtimes
nodejs
npm
jdk17-openjdk
gradle
go
bun-bin

# Development Tools
git
docker
docker-compose
opencode-bin
github-cli
beekeeper-studio-bin

# Multimedia
vlc
discord
obs-studio
gnome-sound-recorder

# VPN
openvpn

# Virtualization
qemu-desktop

# Office Suite
libreoffice-fresh

# Utilities
7zip
fastfetch
etcher-bin
gparted
