# List of packages to be installed
#
# Browsers
firefox
brave-bin

# Shell
zsh

# Terminal Emulator
kitty

# File Manager
thunar

# Email Client
thunderbird

# Text Editor
neovim
visual-studio-code-bin
obsidian

# System Monitoring Tools
htop
btop
nvtop
radeontop

# Networking Tools
curl
wget
postman-bin
net-tools
openbsd-netcat

# Programming Languages and Runtimes
nodejs
npm
jdk17-openjdk
gradle
go

# Development Tools
git
docker
docker-compose
opencode-bin
github-cli

# Multimedia
obs-studio
gnome-sound-recorder

# Utilities
fastfetch
lib32-mesa
lib32-vulkan-icd-loader
lib32-vulkan-radeon
vulkan-radeon
