# -------------------------------- Custom packages -------------------------------------------

# ---- ---- bootloader ---- ----
# limine
# limine-mkinitcpio-hook
# limine-snapper-sync
# snapper


# ---- ---- desktop environment ---- ----
# Gnome
gnome-keyring
gnome-themes-extra
polkit-gnome
xdg-desktop-portal-gtk
xdg-terminal-exec

# KDE
kvantum-qt5
qt5-wayland
sddm

# Hyprland
hyprland
hypridle
hyprland-guiutils
hyprlock
hyprpicker
hyprshot
hyprsunset
xdg-desktop-portal-hyprland

# Desktop Bar
waybar

# Sway background
swaybg
swayosd

# Nofification manager
mako

# Boot splash screen
plymouth

# Power management
power-profiles-daemon

# Screeshot
satty
slurp

# App launcher
uwsm

# Start menu
walker

# Clipboard
wl-clipboard
wl-clip-persist

# Other
zram-generator

# ---- ---- Wifi ---- ----
impala
wireless-regdb

# ---- ---- Bluetooth ---- ----
blueberry

# ---- ---- Audio ---- ----
gst-plugin-pipewire
libpulse
pamixer
pipewire
pipewire-alsa
pipewire-jack
pipewire-pulse
playerctl
wiremix
wireplumber

# ---- ---- Brightness ---- ----
brightnessctl

# ---- ---- Fonts ---- ----
noto-fonts
noto-fonts-cjk
noto-fonts-emoji
noto-fonts-extra
ttf-cascadia-mono-nerd
ttf-iawriter-nerd
ttf-jetbrains-mono-nerd
ttf-firecode-nerd
woff2-font-awesome

# ---- ---- Graphics ---- ----
lib32-mesa
lib32-vulkan-icd-loader
lib32-vulkan-radeon
mesa-utils
vulkan-radeon

# ---- ---- Theme ---- ----
yaru-icon-theme

# ---- ---- Browsers ---- ----
firefox

# ---- ---- File system ---- ----
btrfs-progs

# ---- ---- Shell ---- ----
zsh
starship

# ---- ---- Terminal Emulator ---- ----
kitty

# ---- ---- File Manager ---- ----
thunar
nautilus

# ---- ---- Email Client ---- ----
thunderbird

# ---- ---- Text Editor ---- ----
neovim
obsidian

# --- ---- Dotfiles Manager ---- ----
chezmoi

# ---- ---- Networking Tools ---- ----
curl
wget
net-tools
openbsd-netcat
inetutils
nss-mdns
ufw
ufw-docker
whois

# ---- ---- Programming Languages and Runtimes ---- ----
nodejs
npm
jdk17-openjdk
gradle
go
clang
cmake
rust

# ---- ---- Development Tools ---- ----
git
docker
docker-buildx
docker-compose
tmux
github-cli
gum
jq
lazydocker
lazygit
mariadb-libs
mise
ninja
postgresql-libs
tree-sitter-cli
xmlstarlet

# ---- ---- Multimedia ---- ----
# Audio/Video
vlc
mpv
ffmpegthumbnailer
obs-studio
gnome-sound-recorder

# Social Media
discord

# Image/Document viewer
evince
imagemagick
imv

# File sharing
localsend

# General app
gnome-calculator

# ---- ---- VPN ---- ----
openvpn

# ---- ---- Virtualization ---- ----
qemu-desktop

# ---- ---- Office Suite ---- ----
libreoffice-fresh

# ---- ---- Utilities ---- ----
# System Monitoring Tools
htop
btop
nvtop
radeontop

# Archive
7zip
unzip

# System Info
fastfetch

# Partition manager
gparted
asdcontrol
base-devel
gpu-screen-recorder

# managing fonts
fontconfig

# fuzzy finder
fzf

# file manager addons
gvfs-mtp
gvfs-nfs
gvfs-smb

# Full featured CLI system information tool
inxi

# calculator
libqalculate

# yaml support
libyaml


# Terminal utils
rsync
# better grep
ripgrep
# better cd
zoxide
# cat with syntax highlight
bat
# visualyse directory usage
dust
# visualyse pacman database with queries
expac
# ls with style
eza
# find but better
fd

# Other
llvm
less
man-db
inotify-tools
tldr

# ---- Printing ----
cups
cups-browsed
cups-filters
cups-pdf
system-config-printer


# ---- AUR ----
# aether
# bun-bin
# elephant
# elephant-bluetooth
# elephant-calc
# elephant-clipboard
# elephant-desktopapplications
# elephant-files
# elephant-menus
# elephant-providerlist
# elephant-runner
# elephant-symbols
# elephant-todo
# elephant-unicode
# elephant-websearch
# tzupdate
# visual-studio-code-bin
# wayfreeze-git
# etcher-bin
# postman-bin
# beekeeper-studio-bin


# ---- Possibly Unused ----
# luarocks
# omarchy-keyring
# omarchy-nvim
# omarchy-walker
# plocate
# python-gobject
# python-poetry-core
# python-terminaltexteffects
# sushi
# tig
# tldr

