#!/bin/bash
# Automated Limine UEFI Installation Script with Snapper Support
# Based on https://wiki.archlinux.org/title/Limine

set -e

source ../lib/print.sh

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    print_error "Please run as root"
    exit 1
fi

# Get ESP partition
print_info "Detecting ESP partition..."
ESP_PATH=$(bootctl --print-esp-path 2>/dev/null || echo "")

if [ -z "$ESP_PATH" ]; then
    print_warning "Could not auto-detect ESP partition"
    read -p "Enter ESP mount point (e.g., /boot or /boot/efi): " ESP_PATH
    
    if [ ! -d "$ESP_PATH" ]; then
        print_error "Directory $ESP_PATH does not exist"
        exit 1
    fi
fi

print_info "Using ESP: $ESP_PATH"

USE_SNAPSHOTS=true
INITRAMFS_TOOL="mkinitcpio"
LIMINE_TOOL_PKG="limine-mkinitcpio-hook"


print_info "Will use $INITRAMFS_TOOL with $LIMINE_TOOL_PKG"

# Create Limine config
ROOT_UUID=$(lsblk "$DISK" -no UUID | head -n 1)
echo "Using UUID: $ROOT_UUID"

MACHINE_ID=$(cat /etc/machine-id)
echo "Machine ID: $MACHINE_ID"

# Detect filesystem type
ROOT_FSTYPE=$(lsblk -no FSTYPE -o UUID | grep -B1 "$ROOT_UUID" | head -1 || echo "unknown")

# Get btrfs subvolume info if applicable
ROOT_SUBVOL=""
SNAPSHOTS_SUBVOL=""
print_info "Detected filesystem: $ROOT_FSTYPE"

ROOT_SUBVOL="/@"

SNAPSHOTS_SUBVOL="/@.snapshots"

print_info "Root subvolume: $ROOT_SUBVOL"
print_info "Snapshots subvolume: $SNAPSHOTS_SUBVOL"

# Construct kernel cmdline
KERNEL_CMDLINE="root=UUID=$ROOT_UUID rootflags=subvol=$ROOT_SUBVOL rw rootfstype=$ROOT_FSTYPE quiet splash"

echo ""
print_info "Installing limine package..."
pacman -S --needed --noconfirm limine

# Install snapshot-related packages if enabled
if [ "$USE_SNAPSHOTS" = true ]; then
    echo ""
    print_info "Installing snapshot packages..."
    
    # Install snapper and snap-pac
    pacman -S --needed --noconfirm snapper snap-pac jdk17-openjdk
    
    # Check if yay is available for AUR packages
    if command -v yay &> /dev/null; then
        print_info "Installing AUR packages with yay..."
        yay -S --needed --noconfirm "$LIMINE_TOOL_PKG" limine-snapper-sync
    else
        print_warning "Yay not found - please install AUR packages manually:"
        print_warning "  $LIMINE_TOOL_PKG"
        print_warning "  limine-snapper-sync"
        exit 1
    fi
fi

echo ""
print_info "Creating Limine directories..."
mkdir -p "$ESP_PATH/EFI/limine"

echo ""
print_info "Copying Limine UEFI binary..."
cp /usr/share/limine/BOOTX64.EFI "$ESP_PATH/EFI/limine/"

echo ""
print_info "Creating limine.conf..."

# Create config with or without snapshot markers
if [ "$USE_SNAPSHOTS" = true ]; then
    cat > "$ESP_PATH/EFI/limine/limine.conf" << EOF
# Limine Configuration with Snapper Integration
# Auto-generated by install-limine-uefi.sh

timeout: 5

/+Arch Linux
$([ -n "$MACHINE_ID" ] && echo "    comment: machine-id=$MACHINE_ID")
    //Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    cmdline: $KERNEL_CMDLINE
    module_path: boot():/initramfs-linux.img
    
    //Snapshots

/Arch Linux (fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    cmdline: $KERNEL_CMDLINE
    module_path: boot():/initramfs-linux-fallback.img
EOF
else
    cat > "$ESP_PATH/EFI/limine/limine.conf" << EOF
# Limine Configuration
# Auto-generated by install-limine-uefi.sh

timeout: 5

/Arch Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    cmdline: $KERNEL_CMDLINE
    module_path: boot():/initramfs-linux.img

/Arch Linux (fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    cmdline: $KERNEL_CMDLINE
    module_path: boot():/initramfs-linux-fallback.img
EOF
fi

print_info "limine.conf created at $ESP_PATH/EFI/limine/limine.conf"

# Configure Snapper if enabled
if [ "$USE_SNAPSHOTS" = true ]; then
    echo ""
    print_info "Configuring Snapper..."
    
    # Create snapper config for root if it doesn't exist
    if [ ! -d "/.snapshots" ]; then
        print_info "Creating Snapper configuration for root..."
        snapper -c root create-config /
        
        # Delete the subvolume created by snapper (we want to use existing layout)
        if [ -d "/.snapshots" ] && [ "$ROOT_FSTYPE" = "btrfs" ]; then
            btrfs subvolume delete /.snapshots 2>/dev/null || true
            mkdir -p /.snapshots
        fi
    else
        print_info "Snapper config already exists"
    fi
    
    # Configure limine-snapper-sync
    echo ""
    print_info "Configuring limine-snapper-sync..."
    
    # Check if config needs updating
    LIMINE_CONFIG="/etc/default/limine"
    mkdir -p /etc/default
    
    # Create or update config
    cat > "$LIMINE_CONFIG" << EOF
# Limine Snapper Sync Configuration
# Auto-generated by install-limine-uefi.sh

ESP_PATH="$ESP_PATH"
ROOT_SUBVOLUME_PATH="$ROOT_SUBVOL"
ROOT_SNAPSHOTS_PATH="$SNAPSHOTS_SUBVOL"
MAX_SNAPSHOT_ENTRIES=3
LIMIT_USAGE_PERCENT=85
EOF
    
    print_info "Configuration saved to $LIMINE_CONFIG"
    
    # Test limine-snapper-sync if it's installed
    if command -v limine-snapper-sync &> /dev/null; then
        echo ""
        print_info "Testing limine-snapper-sync..."
        if limine-snapper-sync; then
            print_info "limine-snapper-sync test successful"
            
            # Enable the service
            print_info "Enabling limine-snapper-sync.service..."
            systemctl enable --now limine-snapper-sync.service
            
            print_info "Snapshot synchronization is now active"
        else
            print_warning "limine-snapper-sync test failed - check configuration"
        fi
    else
        print_warning "limine-snapper-sync not installed yet"
        print_warning "Install it from AUR and run: systemctl enable --now limine-snapper-sync.service"
    fi
fi

echo ""
print_info "Creating EFI boot entry..."
efibootmgr \
    --create \
    --disk "$DISK" \
    --part "$PART_NUM" \
    --label "Arch Linux Limine Bootloader" \
    --loader '\EFI\limine\BOOTX64.EFI' \
    --unicode

echo ""
print_info "Creating pacman hook for automatic updates..."
mkdir -p /etc/pacman.d/hooks

cat > /etc/pacman.d/hooks/99-limine.hook << 'EOF'
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = limine

[Action]
Description = Deploying Limine after upgrade...
When = PostTransaction
Exec = /usr/bin/cp /usr/share/limine/BOOTX64.EFI ESP_PATH_PLACEHOLDER/EFI/limine/
EOF

# Replace ESP_PATH placeholder
sed -i "s|ESP_PATH_PLACEHOLDER|$ESP_PATH|g" /etc/pacman.d/hooks/99-limine.hook

echo ""
print_info "Current EFI boot entries:"
efibootmgr

echo ""
print_info "=========================================="
print_info "Limine installation complete!"
print_info "=========================================="
print_info "Configuration file: $ESP_PATH/EFI/limine/limine.conf"
print_info "Kernel cmdline: $KERNEL_CMDLINE"

if [ "$USE_SNAPSHOTS" = true ]; then
    echo ""
    print_info "Snapshot Configuration:"
    print_info "  - Snapper is configured for root"
    print_info "  - Root subvolume: $ROOT_SUBVOL"
    print_info "  - Snapshots subvolume: $SNAPSHOTS_SUBVOL"
    print_info "  - limine-snapper-sync.service is enabled"
    print_info "  - Config: /etc/default/limine"
    echo ""
    print_info "Snapshot commands:"
    print_info "  limine-snapper-sync      - Sync snapshots to boot entries"
    print_info "  limine-snapper-list      - List snapshot entries"
    print_info "  limine-snapper-info      - Show detailed info"
    print_info "  limine-snapper-restore   - Restore from snapshot"
    print_info "  snapper list             - List all snapshots"
    print_info "  snapper create --description 'Before X' - Create snapshot"
fi

echo ""
print_warning "Please review the configuration before rebooting"
print_warning "Edit $ESP_PATH/EFI/limine/limine.conf if needed"
echo ""
print_info "To view the config:"
print_info "  cat $ESP_PATH/EFI/limine/limine.conf"
echo ""
print_info "To manage boot order:"
print_info "  efibootmgr"

if [ "$USE_SNAPSHOTS" = true ]; then
    echo ""
    print_warning "Note: ESP should be at least 2GB for snapshot entries"
    print_warning "Check ESP usage with: df -h $ESP_PATH"
fi
